=== birdsinyourgarden/dtd/catalogo/catalogo.dtd
<!ELEMENT catalogo (libro+)>

<!ELEMENT libro (titulo, autor, anio, categorias?)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

<!ELEMENT categorias (categoria+)>
<!ELEMENT categoria (#PCDATA)>

=== birdsinyourgarden/dtd/catalogo/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
    <libro>
    <titulo>El Quijote</titulo>
    <autor>Miguel de Cervantes</autor>
    <anio>1605</anio>
    <categorias>
        <categoria>Novela</categoria>
        <categoria>Cl√°sico</categoria>
    </categorias>
    </libro>
</catalogo>
