=== birdsinyourgarden/dtd/externo1.dtd
<!ELEMENT tareas (tareas+)>
    <!ELEMENT tarea (titulo, descripcion, estado)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT estado (#PCDATA)>

=== birdsinyourgarden/dtd/mixto.xml
<?xml version="1.0" encoding="UTF-8">
<!DOCTYPE tareas SYSTEM "externo1.dtd"[
    <!ELEMENT estado (#PCDATA)>
]>
<tareas>
    <tarea>
        <titulo>Estudiar XML</titulo>
        <descripcion>Repasar DTD y esquemas</descripcion>
        <estado>No completada</estado>
    </tarea>
        <tarea>
        <titulo>Hacer ejercicio</titulo>
        <descripcion>Salir a correr 1 hora</descripcion>
        <estado>Completada</estado>
    </tarea>
</tareas>
